<?php

/**
 * Implements hook_theme().
 */
function vimeo_field_theme($existing, $type, $theme, $path) {
  return [
    'vimeo_video_formatter' => [
      'variables' => ['width' => NULL, 'height' => NULL, 'url' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function vimeo_field_preprocess_node(&$variables) {
  if ($variables['node']->get('type')->getString() == 'media_element') {
    $variables['#attached']['library'][] = 'vimeo_field/popup';
  }
}
